version: "3.9"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    networks:
      - db_network
    ports:
      - "9200:9200"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "xpack.security.http.ssl.enabled=false"
    networks:
      - db_network
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'cryptobot'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/data/db
    networks:
      - db_network
  populate_into_elastic:
    image: projet_final/populate_into_elasticsearch:0.0.1
    container_name: populate_into_elasticsearch
    depends_on:
      - kibana
    environment:
      api_key: '7FipgVGJTbxWEyeyI5wNRyKuQwXXJcRIJBZvvQAxRY1aScVExHzdyQFMh3bLLPT5'
      api_secret: 'tnlNDg4WOt0xungysd7fAZAVKyBqqOzcgQW8MYebVo1piJzfeUC1mYkcDgJSm4T1'
      URL_ELASTIC: 'http://elasticsearch:9200'
    networks:
      - db_network
  populate_into_mysql:
    image: projet_final/populate_into_mysql:0.0.1
    container_name: populate_into_mysql
    depends_on:
      - db
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'cryptobot'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_PORT: "3306"
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_TABLENAME: "botmarche"
      api_key: '7FipgVGJTbxWEyeyI5wNRyKuQwXXJcRIJBZvvQAxRY1aScVExHzdyQFMh3bLLPT5'
      api_secret: 'tnlNDg4WOt0xungysd7fAZAVKyBqqOzcgQW8MYebVo1piJzfeUC1mYkcDgJSm4T1'
    networks:
      - db_network
  api:
    image: projet_final/api:0.0.1
    container_name: api
    depends_on:
      - populate_into_mysql
    ports:
      - "8000:8000"
    networks:
      - db_network
  model:
    image: projet_final/model:0.0.1
    container_name: model
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - db_network
networks:
  db_network:
    name: mysql_net
volumes:
  db-data:
    name: mysql-data