version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - mysql_network
    environment:
      MYSQL_DATABASE: 'cryptobot'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  populate:
    image: populate_base_mysql:latest
    container_name: populate_mysql_data_binance
    depends_on:
      - mysql
    networks:
      - mysql_network
# Names our volume
volumes:
  my-db: