version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'cryptobot'
      MYSQL_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: populate_into_mysql
    container_name: populate_into_mysql
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      #MYSQL_HOST: 'localhost'
      MYSQL_DATABASE: 'cryptobot'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'

volumes:
  mysql_data:
    driver: local