version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'cryptobot'
      MYSQL_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DB: 'cryptobot'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'

volumes:
  dbdata: