version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'cryptobot'
      MYSQL_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: populate_into_mysql
    container_name: populate_into_mysql
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'cryptobot'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_PORT: "3306"
      MYSQL_TABLENAME: "botmarche"
      api_key: '7FipgVGJTbxWEyeyI5wNRyKuQwXXJcRIJBZvvQAxRY1aScVExHzdyQFMh3bLLPT5'
      api_secret: 'tnlNDg4WOt0xungysd7fAZAVKyBqqOzcgQW8MYebVo1piJzfeUC1mYkcDgJSm4T1'

volumes:
  mysql_data:
    driver: local