version: '3.9'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  mysql_data:
    driver: local