version: '3.9'

services:
  api:
    image: api_model
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service_model
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
volumes:
  mysql_data:
    driver: local